[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=tweakml --cov-report=html --cov-config=.coveragerc"
testpaths = [
    "tests",
]